name: Format PR Code
on:
  pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dotnet-format:
    runs-on: windows-latest

    steps:
      - name: Manual checkout by SHA (bypass bad ref name)
        run: |
          git init
          git remote add origin https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
          git fetch origin ${{ github.event.pull_request.head.sha }} --depth=1
          git checkout FETCH_HEAD

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.x

      - name: Run dotnet format
        run: |
          dotnet format .\Microsoft.Maui.sln --no-restore --exclude Templates/src --exclude-diagnostics CA1822
          git diff

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          # Giữ nguyên branch name payload để test injection
          git commit -m "[housekeeping] Automated PR to fix formatting errors on ${{ github.head_ref }}" || echo "No changes to commit"

      - name: Push changes to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Giữ nguyên branch name payload để test injection
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
